# Generated by Django 2.1.4 on 2018-12-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181216_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self', to='webapp.Article', verbose_name='Отношение'),
        ),
    ]
