# Generated by Django 2.1.4 on 2018-12-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181216_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related', to='webapp.Comment', verbose_name='Отношение'),
        ),
    ]
