# Generated by Django 2.1.4 on 2018-12-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181216_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='relation',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_to_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='webapp.Article', verbose_name='Отношение'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='webapp.Comment', verbose_name='Отношение'),
        ),
    ]
