# Generated by Django 2.1.4 on 2018-12-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181216_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.PROTECT, to='webapp.Blogger', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_to_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='webapp.Article', verbose_name='Комментарий к статье'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='webapp.Comment', verbose_name='Комментарий к комментарию'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(blank=True, choices=[(1, 'ужасно'), (2, 'плохо'), (3, 'нормально'), (4, 'хорошо'), (5, 'отлично')], max_length=20, null=True, verbose_name='Оценка'),
        ),
    ]
