# Generated by Django 2.1.4 on 2018-12-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20181216_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Blogger'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='webapp.Blogger', verbose_name='Оценивающий'),
        ),
    ]
