# Generated by Django 2.1.4 on 2018-12-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20181216_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite',
            new_name='article',
        ),
    ]
