# Generated by Django 2.1.4 on 2018-12-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20181219_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.PROTECT, related_name='blog_author', to='webapp.Blogger', verbose_name='Автор'),
        ),
    ]
