# Generated by Django 2.1.4 on 2018-12-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20181219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_mark', to='webapp.Article', verbose_name='Отношение'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='blogger_mark', to='webapp.Blogger', verbose_name='Оценивающий'),
        ),
    ]
