# Generated by Django 2.1.4 on 2018-12-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20181220_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(blank=True, choices=[('1', 'ужасно'), ('2', 'плохо'), ('3', 'нормально'), ('4', 'хорошо'), ('5', 'отлично')], max_length=20, null=True, verbose_name='Оценка'),
        ),
    ]
